language: node_js
node_js:
 - "8"
dist: trusty
#sudo: required
#addons:
#  chrome: stable
#before_install:
  # start your web application and listen on `localhost`
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#services:
#  - mongodb  
#before_script:
#    - "sudo chown root /opt/google/chrome/chrome-sandbox"
#    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
#    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install: 
  - npm install
  - npm run build
script: 
  - nohup npm run start &
#  - sleep 3
#  - npm run test #disable the tests due to a sandbox issue i puppeteer